# Generated by Django 4.0.6 on 2022-07-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200702_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
