# Generated by Django 4.0.6 on 2022-07-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_bankdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_id',
            field=models.CharField(max_length=10),
        ),
    ]
